package HandlingArrayException;


import java.io.*;
class Test45 
{
	public static void main(String[] args) throws Exception 
	{
		methodA();
	}

	public static void methodA() throws IOException
	{
		System.out.println("Completed..");
	}
}